service: admin-lambda

package:
  include: template/**

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": AdminGateWay-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": AdminGateway-rootResourceId
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource: "*"

functions:
  newRound:
    handler: newRound.lambda_handler
    events:
      - http:
          path: new-round
          method: post
  homePage:
    handler: index.lambda_handler
    events:
      - http:
          path: home
          method: get

plugins:
  - serverless-python-requirements
