service: admin-lambda

package:
  include: template/**

provider:
  name: aws
  runtime: python3.9
  region: us-east-1
  apiGateway:
    restApiId:
      "Fn::ImportValue": AdminGateWay-restApiId
    restApiRootResourceId:
      "Fn::ImportValue": AdminGateway-rootResourceId
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
            - lambda:InvokeFunction
            - lambda:InvokeAsync
          Resource: "*"

functions:
  status:
    handler: status.lambda_handler
    events:
      - http:
          path: status
          method: get
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request 
  newRound:
    handler: newRound.lambda_handler
    events:
      - http:
          path: new-round
          method: post
          cors: true
          authorizer:
            name: authorizerFunc
            resultTtlInSeconds: 0
            identitySource: method.request.header.Authorization
            type: request
  login:
    handler: login.lambda_handler
    events:
      - http:
          path: login 
          method: post
          cors: true
  homePage:
    handler: index.lambda_handler
    events:
      - http:
          path: home
          method: get
          cors: true
  authorizerFunc:
    handler: auth.lambda_handler

plugins:
  - serverless-python-requirements
