service: api-gateway-admin

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

resources:
  Resources:
    Gateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: meetup-admin
  Outputs:
    apiGatewayRestApiId:
      Value:
        Ref: Gateway
      Export:
        Name: Gateway-restApiId
    apiGnaatewayRestApiRootResourceId:
      Value:
        Fn::GetAtt:
          - Gateway
          - RootResourceId
      Export:
        Name: Gateway-rootResourceId
